<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <PackageTags>NuGet;Git</PackageTags>
    <Description>The libraries to host BaGetter on Git repositories.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaGetter.Core\BaGetter.Core.csproj" />
  </ItemGroup>

</Project>
